#include<iostream>
using namespace std;
int main(){
    int i;
    cout << "Garbage value: " <<i<<endl; //garbage value is random val generated by compiler , we should avoid generating this
    return 0;
}
